### PR TITLE
Adds some more fields ! YAYYYY

### PR DESCRIPTION
**Pull request by SaraVieira**
* Adds prettier 
 * Adds position
 * Adds size
 * Adds Style (
	    type Style {
        fontFamily: String
        fontPostScriptName: String
        fontWeight: Int
        fontSize: Float,
        textAlignHorizontal: String,
        textAlignVertical: String,
        letterSpacing: Float,
        lineHeightPx: Float,
        lineHeightPercent: Int
    }
) 
 * Adds strokeWeight,
 * Adds strokeAlign,
 * Adds strokes

use pgDp5TDS2aSBkUrcUZpbsc to test strokes

### CODE REVIEW

**Comment by SaraVieira** [comment]
@braposo Can we replace graphiql for https://github.com/graphcool/graphql-playground ?

It's way nicer

**Comment by braposo** [comment]
Thanks for the PR @SaraVieira, this looks amazing! I'm going to merge this, update the examples and add `graphql-playground` (thanks for the suggestion as well!) for the next release.

**Comment by SaraVieira** [comment]
Awesome!! I'm gonna try and add more stuff today 👌

**Comment by braposo** [comment]
I've just done that @SaraVieira, it's now live at https://www.graphqlbin.com/v2/lOM4TX

Also added position and size to the frames since it was already done for the elements anyway.

**Pull request merged**
