### PR TITLE
Re-think Figma data

### PR DESCRIPTION
**Pull request by braposo**
So this PR contains big changes to the way we process the Figma API.

We are now processing the response from the API and building our own structure that enables a few more features than the previous version.

The most visible change is the creation shortcuts that surface all the children of a given node, no matter where they are down in the tree, and group them by type. This simplifies the queries and the resolvers a lot so I got rid of some of the previous logic that required external libraries to traverse the tree.

We can now do something like this: 

```gql
{
  file(id: "cLp23bR627jcuNSoBGkhL04E") {
    name
    frameScreenshots: frames {
      image
    }
    groups {
      id
      name
      rectangles {
        id
        name
      }
    }
    pages {
      name
      id
      frames {
        id
        name
      }
      texts {
        characters
      }
    }
  }
}
```
That will return:
```json
{
  "data": {
    "file": {
      "name": "figma-graphql test file",
      "frameScreenshots": [
        {
          "image": "https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/7e99/bb40/8841786de5992873a18a2d9e07bd45f3"
        },
        {
          "image": null
        },
        {
          "image": "https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/bdd6/12a4/a927cfbf477351913f9dc3c98db33a64"
        }
      ],
      "groups": [
        {
          "id": "56:6",
          "name": "Group",
          "rectangles": [
            {
              "id": "28:6",
              "name": "Rectangle"
            }
          ]
        }
      ],
      "pages": [
        {
          "name": "Page 1",
          "id": "0:1",
          "frames": [
            {
              "id": "7:0",
              "name": "Frame 1"
            },
            {
              "id": "46:0",
              "name": "Frame 1.1"
            }
          ],
          "texts": [
            {
              "characters": "Text"
            },
            {
              "characters": "Text"
            },
            {
              "characters": "Text"
            },
            {
              "characters": "Hello"
            }
          ]
        },
        {
          "name": "Page 2",
          "id": "28:4",
          "frames": [
            {
              "id": "28:5",
              "name": "Frame"
            }
          ],
          "texts": []
        }
      ]
    }
  }
}
```

This makes the API much more powerful and easy to use by anyone as most people don't really care about the structure of the elements in the files.

If they still care about the structure they can still do it by using the `children` property like this:
```gql
{
  file(id: "cLp23bR627jcuNSoBGkhL04E") {
    name
    thumbnailUrl
    lastModified
    pages {
      name
      id
      type
      frames {
        id
        name
        children {
          id
          name
          type
          ... on Component {
            size {
              height
              width
            }
          }
          ... on Group {
            visible
          }
        }
      }
    }
  }
}
```
which returns:
```json
{
  "data": {
    "file": {
      "name": "figma-graphql test file",
      "thumbnailUrl": "https://s3-alpha-sig.figma.com/thumbnails/6ae4af49-e3e5-42c8-9f52-313e4e716586?Expires=1559520000&Signature=N8ngjOlG2NSpntECBsefztk-p~t8TrhpDkRM-8TmWuT57BXhoXQyWU5r68xeoWqySSdNQpCi0FAvuHDanOPA9Tf6aGNzguv-exVr~98YeE2r0rUSstN1u6EkDvE-iyvLamkWfbOgxrfnvT6ajSuFpM5JSsz8zPJMse4Zc7aXeOm41kW6PL0JeYaUFrdOvy16shuO3uHfbu6CRqXE~26xD6hHW8~kkhD8qaS6U7g2O-7MT8Poc93NRGFXSP4z1HODxyDifkGPzPxKzt89bNLd09B~BP0MCE8l5GiP7cqxABEVuWvCCAn05EHDMso-yYYceGI5gi-hshiotCRXDrYbag__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
      "lastModified": "2019-05-25T08:57:55.609098Z",
      "pages": [
        {
          "name": "Page 1",
          "id": "0:1",
          "type": "CANVAS",
          "frames": [
            {
              "id": "7:0",
              "name": "Frame 1",
              "children": [
                {
                  "id": "1:5",
                  "name": "Rectangle",
                  "type": "COMPONENT",
                  "size": {
                    "height": 109,
                    "width": 201
                  }
                }
              ]
            },
            {
              "id": "46:0",
              "name": "Frame 1.1",
              "children": [
                {
                  "id": "46:1",
                  "name": "Rectangle",
                  "type": "INSTANCE"
                }
              ]
            }
          ]
        },
        {
          "name": "Page 2",
          "id": "28:4",
          "type": "CANVAS",
          "frames": [
            {
              "id": "28:5",
              "name": "Frame",
              "children": [
                {
                  "id": "56:6",
                  "name": "Group",
                  "type": "GROUP",
                  "visible": true
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```
The `children` property will only return the elements that are direct descendants of the node, only the shortcuts can be used to access any element down the tree.

This also extends the current schema to include what's missing from the Figma API.

Next step is to add tests for each of the types so we are sure that it's getting everything we want from the API.

### CODE REVIEW

**Comment by braposo** [comment]
@SaraVieira @okonet don't know if you want to have a look but I appreciate any feedback you might have!

You can run this in CodeSandbox using: https://codesandbox.io/s/github/braposo/figma-graphql/tree/normalise-figma-data

**Comment by okonet** [comment]
That’s cool! I’m wondering how idiomatic GraphQL it is, though. But I think it’s a good step forward in terms of simplicity.

**Comment by braposo** [comment]
thanks for commenting @okonet! I see what you mean but I still think it's quite inline with what GraphQL is made for: getting the exact information we need from a data source. 

In this case we're just transforming the original data source from Figma API to something a bit more natural as people often don't understand the relationship between the different elements in a design file.

I'll write a bit more of documentation in #24 to show how this new API can be useful in many different scenarios.

**Comment by okonet** [comment]
Yeah totally on your side. I’m just wondering if at this point it would make sense to involve Figma. Let me try to get the connection and see what they think.

**Pull request merged**
